server:
  port: 0

spring:
  application:
    name: payment-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: payment${server.port}
    prefer-ip-address: true