server:
  port: 80

spring:
  application:
    name: order-comsume
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: order
    prefer-ip-address: true
