server:
  port: 8001

spring:
  application:
    name: hystrix-payment-provider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
#    instance-id: payment${server.port}